import type { Difficulty,Digit,Grid,Puzzle } from '../sudoku/types';
export type GameMode='classic'|'daily'|'quick'|'zen'|'time-attack';export type MistakeMode='relaxed'|'three-strikes'|'off';
export interface Snapshot{values:Grid;notes:readonly (readonly Digit[])[];mistakes:number;hintsUsed:number;status:GameStatus}
export type GameStatus='playing'|'paused'|'complete'|'failed';
export interface GameState extends Snapshot{id:string;puzzleId:string;original:Grid;solution:Grid;difficulty:Difficulty;mode:GameMode;mistakeMode:MistakeMode;startedAt:number;lastPlayedAt:number;elapsedSeconds:number;countdownSeconds:number|null;selected:number|null;notesMode:boolean;history:readonly Snapshot[];future:readonly Snapshot[];notesUsed:boolean;completionRecorded:boolean;date?:string}
export interface NewGameOptions{mode:GameMode;mistakeMode:MistakeMode;countdownSeconds?:number;date?:string}
export interface Statistics{started:number;completed:number;abandoned:number;totalSeconds:number;currentStreak:number;longestStreak:number;byDifficulty:Record<Difficulty,{completed:number;bestSeconds:number|null}>;completedIds:string[];dailyCompleted:string[]}
export const snapshot=(g:GameState):Snapshot=>({values:g.values,notes:g.notes,mistakes:g.mistakes,hintsUsed:g.hintsUsed,status:g.status});
export function createGame(p:Puzzle,o:NewGameOptions):GameState{const parse=(s:string)=>Object.freeze([...s].map(Number)) as Grid;return{id:`${o.mode}:${o.date??p.id}:${Date.now()}`,puzzleId:p.id,original:parse(p.puzzle),solution:parse(p.solution),values:parse(p.puzzle),notes:Object.freeze(Array.from({length:81},()=>Object.freeze([] as Digit[]))),difficulty:p.difficulty,mode:o.mode,mistakeMode:o.mistakeMode,startedAt:Date.now(),lastPlayedAt:Date.now(),elapsedSeconds:0,countdownSeconds:o.countdownSeconds??null,selected:null,notesMode:false,mistakes:0,hintsUsed:0,status:'playing',history:[],future:[],notesUsed:false,completionRecorded:false,date:o.date}}
