import type { ThemeId } from '../config/themes';import type { GameState,Statistics } from '../game/types';export type {Statistics} from '../game/types';import type { Difficulty } from '../sudoku/types';
export interface Settings{theme:ThemeId;preferredDifficulty:Difficulty;inputMode:'cell-first'|'number-first';mistakeMode:'relaxed'|'three-strikes'|'off';autoRemoveNotes:boolean;autoCandidates:boolean;preventImpossibleNotes:boolean;commentary:'quiet'|'standard'|'lively';soundEnabled:boolean;soundVolume:number;onboardingComplete:boolean;reducedMotion:boolean}
export interface SavedData{version:3;game:GameState|null;settings:Settings;statistics:Statistics;achievements:string[];recoveryMessage:string|null}
const byDifficulty={easy:{completed:0,bestSeconds:null},medium:{completed:0,bestSeconds:null},hard:{completed:0,bestSeconds:null},expert:{completed:0,bestSeconds:null}};
export const defaults:SavedData={version:3,game:null,settings:{theme:'ink',preferredDifficulty:'easy',inputMode:'cell-first',mistakeMode:'relaxed',autoRemoveNotes:true,autoCandidates:false,preventImpossibleNotes:true,commentary:'standard',soundEnabled:true,soundVolume:.58,onboardingComplete:false,reducedMotion:false},statistics:{started:0,completed:0,abandoned:0,totalSeconds:0,currentStreak:0,longestStreak:0,currentIq:null,bestIq:null,iqHistory:[],byDifficulty,completedIds:[],dailyCompleted:[]},achievements:[],recoveryMessage:null};
const KEY='tomduko:v3';const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
function validGame(g:unknown):g is GameState{if(!g||typeof g!=='object')return false;const x=g as GameState;return Array.isArray(x.values)&&x.values.length===81&&Array.isArray(x.original)&&x.original.length===81&&Array.isArray(x.solution)&&x.solution.length===81}
export function migrate(raw:unknown):SavedData{if(!raw||typeof raw!=='object')return clone(defaults);const d=raw as Partial<SavedData>;const game=validGame(d.game)?d.game:null;return{...clone(defaults),...d,version:3,game,settings:{...defaults.settings,...d.settings},statistics:{...defaults.statistics,...d.statistics,byDifficulty:{...defaults.statistics.byDifficulty,...d.statistics?.byDifficulty}},recoveryMessage:d.game&&!game?'Your saved puzzle was damaged, so it was safely removed. Your statistics remain intact.':null}}
export interface StorageRepository{load():SavedData;save(data:SavedData):boolean;clear():void;available:boolean}
export function createStorage(storage?:Storage):StorageRepository{let available=true;return{get available(){return available},load(){try{const value=(storage??localStorage).getItem(KEY);return value?migrate(JSON.parse(value)):clone(defaults)}catch{available=false;return{...clone(defaults),recoveryMessage:'Local storage is unavailable. Progress will last only for this session.'}}},save(data){try{(storage??localStorage).setItem(KEY,JSON.stringify(data));return true}catch{available=false;return false}},clear(){try{(storage??localStorage).removeItem(KEY)}catch{available=false}}}}
