import {useCallback,useEffect,useReducer,useRef,useState} from 'react';import{useRegisterSW}from'virtual:pwa-register/react';import{GameScreen}from'../components/GameScreen';import{Home}from'../components/Home';import{HowTo,NewGame,SettingsPanel,StatisticsPanel}from'../components/Panels';import{Onboarding}from'../components/Onboarding';import{gameReducer}from'../game/reducer';import{createGame,type GameMode,type GameState}from'../game/types';import{createStorage,type SavedData}from'../persistence/storage';import{puzzleForDate,puzzles,rotatedPuzzle}from'../sudoku/fixtures';import type{Difficulty}from'../sudoku/types';
const repo=createStorage();const today=()=>new Date().toLocaleDateString('en-CA');
export default function App(){
 const [data,setData]=useState<SavedData>(()=>repo.load());
 const [screen,setScreen]=useState(()=>{const requested=sessionStorage.getItem('tomduko:screen');sessionStorage.removeItem('tomduko:screen');return requested==='game'&&data.game?'game':'home'});
 const [game,dispatch]=useReducer(gameReducer,data.game as GameState);const gameRef=useRef(game);gameRef.current=game;
 const {needRefresh:[needRefresh],updateServiceWorker}=useRegisterSW({onRegisterError:()=>{}});
 const save=useCallback((next:SavedData)=>{setData(next);repo.save(next)},[]);
 useEffect(()=>{if(game)repo.save({...data,game})},[game,data]);
 useEffect(()=>{if(!game||game.status!=='playing')return;let last=Date.now();const timer=setInterval(()=>{const now=Date.now(),seconds=Math.floor((now-last)/1000);if(seconds){last+=seconds*1000;dispatch({type:'tick',seconds})}},1000);return()=>clearInterval(timer)},[game]);
 useEffect(()=>{if(!game||game.status!=='complete'||data.statistics.completedIds.includes(game.id))return;const daily=game.mode==='daily'&&game.date&&!data.statistics.dailyCompleted.includes(game.date)?[...data.statistics.dailyCompleted,game.date]:data.statistics.dailyCompleted,diff=data.statistics.byDifficulty[game.difficulty];save({...data,statistics:{...data.statistics,completed:data.statistics.completed+1,totalSeconds:data.statistics.totalSeconds+game.elapsedSeconds,currentStreak:data.statistics.currentStreak+1,longestStreak:Math.max(data.statistics.longestStreak,data.statistics.currentStreak+1),completedIds:[...data.statistics.completedIds,game.id],dailyCompleted:daily,byDifficulty:{...data.statistics.byDifficulty,[game.difficulty]:{completed:diff.completed+1,bestSeconds:diff.bestSeconds===null?game.elapsedSeconds:Math.min(diff.bestSeconds,game.elapsedSeconds)}}},achievements:[...new Set([...data.achievements,'first-grid',...(!game.mistakes&&!game.hintsUsed?['clean']:[])])]})},[game,data,save]);
 const start=(difficulty:Difficulty,mode:GameMode)=>{const date=mode==='daily'?today():undefined,source=puzzles.find(p=>p.difficulty===difficulty)??puzzles[0],puzzle=mode==='daily'?puzzleForDate(date!):rotatedPuzzle(source,`${mode}:${data.statistics.started+1}`),next=createGame(puzzle,{mode,mistakeMode:mode==='zen'?'relaxed':data.settings.mistakeMode,countdownSeconds:mode==='time-attack'?300:undefined,date});repo.save({...data,game:next,statistics:{...data.statistics,started:data.statistics.started+1}});sessionStorage.setItem('tomduko:screen','game');location.reload()};
 if(!data.settings.onboardingComplete)return <Onboarding finish={()=>save({...data,settings:{...data.settings,onboardingComplete:true}})}/>;
 const content=screen==='game'&&game?<GameScreen game={game} dispatch={dispatch} home={()=>setScreen('home')}/>:screen==='new'?<NewGame start={start} back={()=>setScreen('home')}/>:screen==='settings'?<SettingsPanel settings={data.settings} change={settings=>save({...data,settings})} back={()=>setScreen('home')} reset={()=>{repo.clear();location.reload()}}/>:screen==='statistics'?<StatisticsPanel statistics={data.statistics} unlocked={data.achievements} back={()=>setScreen('home')}/>:screen==='how'?<HowTo back={()=>setScreen('home')}/>:<Home game={game} streak={data.statistics.currentStreak} start={start} navigate={setScreen}/>;
 return <div className={`app theme-${data.settings.theme}`}>{data.recoveryMessage&&<div className="recovery">{data.recoveryMessage}</div>}{content}{needRefresh&&<div className="update-toast"><span>A polished new version is ready.</span><button onClick={()=>{repo.save({...data,game:gameRef.current});void updateServiceWorker(true)}}>Update safely</button></div>}</div>
}
